### ISSUE TITLE
Example command for creating a new project named foo hangs forever

### ISSUE THREAD

**Issue by nmrshll** [bitnami/bitnami-docker-codeigniter#74]
When I try to run the example command for creating a new project named `foo`, it hangs forever on the line

`mysql-c INFO Trying to connect to MySQL server`

Here are the complete logs:

```
me@Nicolas-Lenovo-Flex2-15:~/src/gitlab.com/voyagelangue/crm-codeigniter/bitnami-codeigniter/myapp$ docker-compose run myapp nami execute codeigniter createProjec
t foo
Starting myapp_mariadb_1 ...
Starting myapp_mariadb_1 ... done

Welcome to the Bitnami codeigniter container
Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-codeigniter
Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-codeigniter/issues
Send us your feedback at containers@bitnami.com

Starting application ...
mysql-c INFO  Trying to connect to MySQL server
```

Steps to get there: all the above steps from the README, and they seem to work well, the application launches, mariaDB launches, and I can access the default codeigniter application in my browser.

Details:
OS: Ubuntu 16.04.1, linux 4.8.0.46-generic, x86 64 bits
docker version: 17.05.0-ce
docker info: 
```
Containers: 11
 Running: 2
 Paused: 0
 Stopped: 9
Images: 7
Server Version: 17.05.0-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 86
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 9048e5e50717ea4497b757314bad98ea3763c145
runc version: 9c2d8d184e5da67c95d601382adf14862e4f2228
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.8.0-46-generic
Operating System: Ubuntu 16.04.2 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 7.704GiB
Name: Nicolas-Lenovo-Flex2-15
ID: L5QF:DKHK:5VKX:WHHA:DA4H:VB4O:PBDN:EYPH:SLFV:BLVK:ST5E:22B2
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

```

$BITNAMI_IMAGE_VERSION seems to be empty inside both containters (the mariaDB and the myapp one)
I tried displaying it using `docker exec -it 98c3 echo $BITNAMI_IMAGE_VERSION` and same with the other container id, both return nothing

**Comment by juan131** [comment]
Hello @n-marshall 

The problem is that you run `$ docker-compose run myapp nami execute codeigniter createProjec
t foo` without previously create the MySQL container so it's unable to connect to the database. You can simply edit the `docker-compose` file by adding the line below to the environment secttion:

Please run the command:

```
$ docker-compose up -e 
```

And let us know if that works.
