### ISSUE TITLE
XDebug feature

### ISSUE THREAD

**Issue by boskiv** [bitnami/bitnami-docker-codeigniter#77]
**Description**

I want to connect with xdebug from IDE to this image.
Is the official way to do it ?

**Comment by javsalgar** [comment]
Hi,

You may need to enable xdebug in the container. There is a similar case for our php-fpm container and part of the instructions apply, could you check them? 

https://github.com/bitnami/bitnami-docker-php-fpm/issues/18

In your case, you may need to mount your own php.ini file with xdebug enabled.
