### ISSUE TITLE
remove index.php from url

### ISSUE THREAD

**Issue by jjabrane** [bitnami/bitnami-docker-codeigniter#78]
Hello,
At first i would like to thank you about this useful docker for codeigniter application.

does this version contain the htaccess configuration to remove index.php from url.

Many thanks

:)

**Comment by alemorcuq** [comment]
I'm assuming both @jjabrane and @jjab2020 are the same people, so I'm closing this as solved.

**Comment by jjab2020** [comment]
Hello, yes the same person, i have 2 accounts.
Many thanks
