### ISSUE TITLE
Bitnami Codeigniter + AWS ECS / Label: Help Wanted

### ISSUE THREAD

**Issue by adrianboisclair** [bitnami/bitnami-docker-codeigniter#82]
Hi guys

I was wondering if anyone had any experience in using this on AWS Elastic Container Service?

I'm setting up a project now actually, and was stoked to find this for development. Not sure if there this would be ready to deploy as is, or if we need to update some config/file structure.

Thanks!

Adrian

**Comment by miguelaeh** [comment]
Hi @adrianboisclair ,
It should be possible to deploy it by default as it is.. Have you found any kind of issue deploying it?

**Comment by adrianboisclair** [comment]
Thanks! That's all the info I needed. No issues deploying, just read docs and noticed it said "...for development..." but thank you and I appreciate your response. I literally have no idea how that got past me.

**Comment by ramubonkuri** [comment]
Did anyone tried deploying the code igniter application on AWS Elastic Container Service

**Comment by ramubonkuri** [comment]
Looking for documentation or help to deploy the application in AWS ECS for scaling

**Comment by miguelaeh** [comment]
Hi @ramubonkuri ,
Are you getting any issues?
