### ISSUE TITLE
running phpinfo on the apache container

### ISSUE THREAD

**Issue by richb201** [bitnami/bitnami-docker-codeigniter#83]
I am using bitnami/apache docker container. I am trying to connect to the RDS Postgresql  on AWS from my application running in the bitnami/php-fpm container. I have been working with AWS support and they informed me how to make sure the PG driver is loaded in php.ini. I did this but need to run phpinfo() in the apache container to see if my changes took. I don't know how to do this. I tried docker exec 39c /bin/bash, thinking this would allow me to run inside the container. I then did php -a. This opened "interactive mode enabled" and "php >". I now type echo phpinfo() but this doesn't seems to work. I am not even sure if I am in the container! How can I run phpinfo() in the bitnami/apache docker container?

**Comment by javsalgar** [comment]
Hi. Could you try running php -m? That would list the modules that are enabled.

**Comment by richb201** [comment]
Thanks. That sure is a lot easier! Here is the result:
richb201@richb201-XPS-13-9370:~$ php -m
[PHP Modules]
calendar
Core
ctype
date
ereg
exif
fileinfo
filter
ftp
gettext
hash
iconv
json
libxml
mbstring
mcrypt
mhash
mysql
mysqli
mysqlnd
openssl
pcntl
pcre
PDO
pdo_mysql
Phar
posix
readline
Reflection
session
shmop
sockets
SPL
standard
sysvmsg
sysvsem
sysvshm
tokenizer
xdebug
Zend OPcache
zlib

[Zend Modules]
Xdebug
Zend OPcache

Two questions? First, how can I be certain that thiis the php in the container and not on the host? Second, here is my Dockerfile. Notice how it is rebuilding php-fpm? But the php.ini needs to be in the Apache container, right?
FROM bitnami/php-fpm:7.2 as builder
RUN install_packages git autoconf build-essential
WORKDIR /app
RUN wget https://github.com/xdebug/xdebug/archive/2.6.0.tar.gz && \
    tar xzf 2.6.0.tar.gz && \
    cd xdebug-2.6.0 && \
    phpize && \
    ./configure --enable-xdebug && \
    make && make install


FROM bitnami/php-fpm:7.2
COPY --from=builder /opt/bitnami/php/lib/php/extensions/xdebug.so /opt/bitnami/php/lib/php/extensions/
RUN echo 'zend_extension="/opt/bitnami/php/lib/php/extensions/xdebug.so"' >> /opt/bitnami/php/etc/php.ini

RUN echo "xdebug.remote_port=9000" >> /opt/bitnami/php/etc/php.ini \
    && echo "xdebug.remote_enable=1" >> /opt/bitnami/php/etc/php.ini \
    && echo "xdebug.remote_connect_back=0" >> /opt/bitnami/php/etc/php.ini \
    && echo "xdebug.remote_host=192.168.122.1" >> /opt/bitnami/php/etc/php.ini \
    && echo "xdebug.idekey=docker" >> /opt/bitnami/php/etc/php.ini \
    && echo "xdebug.remote_autostart=1" >> /opt/bitnami/php/etc/php.ini \
    && echo "xdebug.remote_log=/tmp/xdebug.log" >> /opt/bitnami/php/etc/php.ini \
    && echo "extension=pgp_pdo_pgsql.so" >> /opt/bitnami/php/etc/php.ini \
    && echo "extension==pgp_pgsql.so" >> /opt/bitnami/php/etc/php.ini

**Comment by javsalgar** [comment]
Hi,

About the first question, you could check the prompt. You should see something like `i have no name` there

**Comment by javsalgar** [comment]
About the second, could you show the exact docker-compose you are using? I would imagine that you would use the codeigniter container as the builder instead.

**Comment by richb201** [comment]
Javier, the answer is no. I am attaching the exact interaction. First here
is my docker ps:
richb201@richb201-XPS-13-9370:~$ docker ps
CONTAINER ID        IMAGE                     COMMAND
 CREATED             STATUS                         PORTS
         NAMES
bf7cd31dd662        bitnami/codeigniter:3     "/app-entrypoint.sh …"   2
days ago          Up 2 days                      0.0.0.0:8000->8000/tcp
      richb201_myapp_1
bef8592ae9db        bitnami/mariadb:10.3      "/entrypoint.sh /run…"   2
days ago          Up 2 days                      3306/tcp
      richb201_mariadb_1
ad0fcddd1a89        bitnami/jasperreports:7   "/app-entrypoint.sh …"   4
days ago          Restarting (1) 2 seconds ago
       docker-substantiator2_jasperreports_1
4822d9765b50        bitnami/php-fpm           "php-fpm -F --pid /o…"   4
days ago          Up 2 days                      9000/tcp
      docker-substantiator2_php-fpm_1
22181bb16474        phpmyadmin/phpmyadmin     "/docker-entrypoint.…"   4
days ago          Up 2 days                      0.0.0.0:8081->80/tcp
      phpmyadmin
39c0610709cc        bitnami/apache:latest     "/entrypoint.sh /run…"   4
days ago          Up 2 days                      8443/tcp, 0.0.0.0:80->8080/tcp
  docker-substantiator2_apache_1
86915e12900c        mysql:5.6                 "docker-entrypoint.s…"   4
days ago          Up 2 days                      0.0.0.0:3306->3306/tcp
      mysql

Here is what happens after I run bash in the apache container:
richb201@richb201-XPS-13-9370:~$ docker exec 39c /bin/bash
richb201@richb201-XPS-13-9370:~$

So when I now run php -i, I think am running on the host!

**Comment by richb201** [comment]
Javier, I am not using a codeigniter container at all (see the docker ps in
the previous email).
Here is the docker-compose:
version: '3'

services:

  apache:
    image: bitnami/apache:latest
    restart: unless-stopped
    ports:
      - 80:8080
    volumes:
      - ./apache/app.conf:/vhosts/app.conf:ro
      - ./app:/app
    networks:
      - net

  mysql:
    container_name: "mysql"
    restart: unless-stopped
    image: mysql:5.6
    environment:
      - MYSQL_DATABASE
      - MYSQL_PASSWORD
      - MYSQL_ROOT_PASSWORD
      - MYSQL_USER
    volumes:
      - data:/var/lib/mysql
      - ./mysql/mysql.sql:/docker-entrypoint-initdb.d/mysql.sql
    ports:
      - "3306:3306"
    networks:
      - net

  phpmyadmin:
    container_name: phpmyadmin
    restart: unless-stopped
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_HOST=mysql
      - PMA_PORT=3306
    ports:
      - "8081:80"
    networks:
      - net

  php-fpm:
    build: ./php
    restart: unless-stopped
    image: bitnami/php-fpm
    volumes:
      - ./app:/app
    environment:
      - XDEBUG_CONFIG="remote_host=192.168.122.1"
    networks:
      - net

  jasperreports:
    image: 'bitnami/jasperreports:7'
    restart: unless-stopped
    environment:
      - MARIADB_HOST=mysql
      - MARIADB_PORT_NUMBER=3306
      - JASPERREPORTS_USERNAME=admin
      - JASPERREPORTS_PASSWORD=bitnami
      - JASPERREPORTS_DATABASE_USER=admin
      - JASPERREPORTS_DATABASE_PASSWORD=xxx
      - JASPERREPORTS_DATABASE_NAME=jasper
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '8080:8080'
    volumes:
      - jasperreports_data:/bitnami
    depends_on:
      - mysql
    networks:
      - net


volumes:
  data:
    driver: local
  jasperreports_data:
    driver:

I am going to attach the Dockerfile so you can see how php.ini is built. I
guess it is the default with a few modifications added at the end (to get
xdebug going).

**Comment by richb201** [comment]
The real question is how can I modify php.ini in bitnami/php-fpm:7.2. Currently my build (Dockerfile) is below. The xdebug part is working fine but the pgsql part is not. 

FROM bitnami/php-fpm:7.2
COPY --from=builder /opt/bitnami/php/lib/php/extensions/xdebug.so /opt/bitnami/php/lib/php/extensions/
RUN echo 'zend_extension="/opt/bitnami/php/lib/php/extensions/xdebug.so"' >> /opt/bitnami/php/etc/php.ini

RUN echo "xdebug.remote_port=9000" >> /opt/bitnami/php/etc/php.ini \
    && echo "xdebug.remote_enable=1" >> /opt/bitnami/php/etc/php.ini \
    && echo "xdebug.remote_connect_back=0" >> /opt/bitnami/php/etc/php.ini \
    && echo "xdebug.remote_host=192.168.122.1" >> /opt/bitnami/php/etc/php.ini \
    && echo "xdebug.idekey=docker" >> /opt/bitnami/php/etc/php.ini \
    && echo "xdebug.remote_autostart=1" >> /opt/bitnami/php/etc/php.ini \
    && echo "xdebug.remote_log=/tmp/xdebug.log" >> /opt/bitnami/php/etc/php.ini \
    && echo "extension=pgp_pdo_pgsql.so" >> /opt/bitnami/php/etc/php.ini \
    && echo "extension==pgp_pgsql.so" >> /opt/bitnami/php/etc/php.ini

**Comment by javsalgar** [comment]
About this

```
richb201@richb201-XPS-13-9370:~$ docker exec 39c /bin/bash
richb201@richb201-XPS-13-9370:~$

```

I think you are missing `-ti` in `docker exec`. Could you try again?

**Comment by javsalgar** [comment]
Hi,

Sorry for not being clear, it should be like this

```
docker exec -ti <name of the container> bash
```

**Comment by richb201** [comment]
Javier, I think I have zeroed in on the problem (once I got phpinfo
running). My Dockerfile is failing to install the php extensions. From the
readme https://github.com/docker-library/docs/blob/master/php/README.md:

FROM php:7.4-fpmRUN apt-get update && apt-get install -y \
		libfreetype6-dev \
		libjpeg62-turbo-dev \
		libpng-dev \
	&& docker-php-ext-configure gd --with-freetype --with-jpeg \
	&& docker-php-ext-install -j$(nproc) gd

I modified the Dockerfile to include an install of the extensions but
that is failing. Here is my Dockerfile. Can you see what is wrong?


FROM bitnami/php-fpm:7.2 as builder
RUN install_packages git autoconf build-essential
WORKDIR /app
RUN wget https://github.com/xdebug/xdebug/archive/2.6.0.tar.gz && \
    tar xzf 2.6.0.tar.gz && \
    cd xdebug-2.6.0 && \
    phpize && \
    ./configure --enable-xdebug && \
    make && make install

RUN apt-get update && apt-get install -y libpq-dev &&
docker-php-ext-install pdo pdo_pgsql

FROM bitnami/php-fpm:7.2
COPY --from=builder /opt/bitnami/php/lib/php/extensions/xdebug.so
/opt/bitnami/php/lib/php/extensions/
RUN echo 'zend_extension="/opt/bitnami/php/lib/php/extensions/xdebug.so"'
>> /opt/bitnami/php/etc/php.ini

RUN echo "xdebug.remote_port=9000" >> /opt/bitnami/php/etc/php.ini \
    && echo "xdebug.remote_enable=1" >> /opt/bitnami/php/etc/php.ini \
    && echo "xdebug.remote_connect_back=0" >> /opt/bitnami/php/etc/php.ini \
    && echo "xdebug.remote_host=192.168.122.1" >> /opt/bitnami/php/etc/php.ini \
    && echo "xdebug.idekey=docker" >> /opt/bitnami/php/etc/php.ini \
    && echo "xdebug.remote_autostart=1" >> /opt/bitnami/php/etc/php.ini \
    && echo "xdebug.remote_log=/tmp/xdebug.log" >>
/opt/bitnami/php/etc/php.ini \
    && echo "extension=pgp_pdo_pgsql.so" >> /opt/bitnami/php/etc/php.ini \
    && echo "extension=pgp_pgsql.so" >> /opt/bitnami/php/etc/php.ini

**Comment by javsalgar** [comment]
Hi,

From what I see, you are using the instructions of Docker Inc's PHP container, not the Bitnami PHP container. The `docker-php-...` functions are not available in our containers. Instead, you would need to compile them yourself.
