### ISSUE TITLE
which bitnami docker image contains the php.ini file?

### ISSUE THREAD

**Issue by richb201** [bitnami/bitnami-docker-codeigniter#84]
I am using both bitnami/apache:latest and also bitnami/php-fpm. I need to update the php.ini to include support for postgresql. Which of these two contains the php.ini? I think it is php-fpm. How can I get a copy of the actual php.ini that you are using in **your container** so I can add the support for postgresql?

**Comment by miguelaeh** [comment]
Hi @richb201 ,
Please have in mind we don't have the context of your project. Could you provide more information?
I guess you have a PHP application inside the PHP container and that you are redirecting queries from the Apache container to the php-fpm one. If you want to connect your PHP application to PostgreSQL you will need to configure the php-fpm container that is the one that will access PostgreSQL.

**Comment by richb201** [comment]
Thank you. Here are the containers I have: apache, mysql, php-fpm, jaspereports. I will show the docker-config at the bottom along with the Dockerfile. These are all bitnami containers, thus I don't have the actual php.ini that is used. I have two modifications to the php.ini. First, I have xdebug enabled. I am developing my app under phpStorm and the debugger seems to be working fine. Now, I am trying to use AWS RDS Postgresql which is an AWS managed copy of Postgres. Why? My clients will upload their own documents to postgres through my app and I need that table to be professionally managed. I will use Jasperreports to create a report for each customer, showing what documents they have uploaded and showing a thumbnail of each. 

The problem I am having is that when I try to initialize my connection (I am using codeigniter) to RDS Postgres,  the call to pg_pconnect() is failing. Seems that pg_pconnect is not accessible from my code. My thought is that pgsql (or pdo_pgsql) is not enabled in php.ini. I proved this by running phpinfo() in the container. So my next idea was to modify the php.ini in the same way that mods to php.ini are working to enable xdebug. That is NOT working. Finally, I am trying to install pdo_pgsql in the Dockerfile. See "RUN apt-get update && apt-get install -y libpq-dev && docker-php-ext-install pdo pdo_pgsql" in the Dockerfile. Note, in my config of the DNS I am using pgsql, not pdo. I will attach the DNS too. 

My php code starts with initializing the database connections, first to mysql, and then to posgres. The mysql (default) works fine.
          $DB1 = $this->load->database('default', TRUE);
          $DB2 = $this->load->database('postgres', TRUE);
With the debugger I walked through the load database for posgres. It tries to call pg_connect() and I get an error that pg_connect doesn't exist! Here is the actual php code within codeigniter that fails:
		$this->conn_id = ($persistent === TRUE)
			? pg_pconnect($this->dsn)
			: pg_connect($this->dsn);   <<<< error occurs here

I get a program exception "call to undefined function pg_connect()". pg_connect is part of php I think. 


docker-compose:
version: '3'
services:
  apache:
    image: bitnami/apache:latest
    restart: unless-stopped
    ports:
      - 80:8080
    volumes:
      - ./apache/app.conf:/vhosts/app.conf:ro
      - ./app:/app
    networks:
      - net

  mysql:
    container_name: "mysql"
    restart: unless-stopped
    image: mysql:5.6
    environment:
      - MYSQL_DATABASE
      - MYSQL_PASSWORD
      - MYSQL_ROOT_PASSWORD
      - MYSQL_USER
    volumes:
      - data:/var/lib/mysql
      - ./mysql/mysql.sql:/docker-entrypoint-initdb.d/mysql.sql
    ports:
      - "3306:3306"
    networks:
      - net

  phpmyadmin:
    container_name: phpmyadmin
    restart: unless-stopped
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_HOST=mysql
      - PMA_PORT=3306
    ports:
      - "8081:80"
    networks:
      - net

  php-fpm:
    build: ./php
    restart: unless-stopped
    image: bitnami/php-fpm
    volumes:
      - ./app:/app
    environment:
      - XDEBUG_CONFIG="remote_host=192.168.122.1"
    networks:
      - net

  jasperreports:
    image: 'bitnami/jasperreports:7'
    restart: unless-stopped
    environment:
      - MARIADB_HOST=mysql
      - MARIADB_PORT_NUMBER=3306
      - JASPERREPORTS_USERNAME=admin
      - JASPERREPORTS_PASSWORD=bitnami
      - JASPERREPORTS_DATABASE_USER=admin
      - JASPERREPORTS_DATABASE_PASSWORD=xxxx
      - JASPERREPORTS_DATABASE_NAME=jasper
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '8080:8080'
    volumes:
      - jasperreports_data:/bitnami
    depends_on:
      - mysql
    networks:
      - net


volumes:
  data:
    driver: local
  jasperreports_data:
    driver: local

Dockerfile:
FROM bitnami/php-fpm:7.2 as builder
RUN install_packages git autoconf build-essential
WORKDIR /app
RUN wget https://github.com/xdebug/xdebug/archive/2.6.0.tar.gz && \
    tar xzf 2.6.0.tar.gz && \
    cd xdebug-2.6.0 && \
    phpize && \
    ./configure --enable-xdebug && \
    make && make install
RUN apt-get update && apt-get install -y libpq-dev && docker-php-ext-install pdo pdo_pgsql

FROM bitnami/php-fpm:7.2
COPY --from=builder /opt/bitnami/php/lib/php/extensions/xdebug.so /opt/bitnami/php/lib/php/extensions/
RUN echo 'zend_extension="/opt/bitnami/php/lib/php/extensions/xdebug.so"' >> /opt/bitnami/php/etc/php.ini

RUN echo "xdebug.remote_port=9000" >> /opt/bitnami/php/etc/php.ini \
    && echo "xdebug.remote_enable=1" >> /opt/bitnami/php/etc/php.ini \
    && echo "xdebug.remote_connect_back=0" >> /opt/bitnami/php/etc/php.ini \
    && echo "xdebug.remote_host=192.168.122.1" >> /opt/bitnami/php/etc/php.ini \
    && echo "xdebug.idekey=docker" >> /opt/bitnami/php/etc/php.ini \
    && echo "xdebug.remote_autostart=1" >> /opt/bitnami/php/etc/php.ini \
    && echo "xdebug.remote_log=/tmp/xdebug.log" >> /opt/bitnami/php/etc/php.ini \
    && echo "extension=pgp_pdo_pgsql.so" >> /opt/bitnami/php/etc/php.ini \
    && echo "extension=pgp_pgsql.so" >> /opt/bitnami/php/etc/php.ini

dsn:
$db['postgres'] = array(
    'dsn' => 'jdbc:postgresql://imagesdatabase.cwymdn16cxes.us-east-1.rds.amazonaws.com:5432/postgres',
    'hostname' => '',
    'username' => 'richb201',
    'password' => 'XXXX',
    'database' => 'images',
    'dbdriver' => 'postgre',  //ok
    'dbprefix' => '',
    'pconnect' => FALSE,
    'db_debug' => (ENVIRONMENT !== 'production'),
    'cache_on' => FALSE,
    'cachedir' => '',
    'char_set' => 'utf8',
    'dbcollat' => 'utf8_general_ci',
    'swap_pre' => '',
    'encrypt' => FALSE,
    'compress' => FALSE,
    'stricton' => FALSE,
    'failover' => array(),
    'save_queries' => TRUE,
    'port'     =>5432
);

**Comment by miguelaeh** [comment]
Hi @richb201 ,
This seems to be a complex and really customized scenario that I can't replicate. I any case, you can get the `php.ini` file running the following command:
```
docker run --rm -it bitnami/php-fpm cat /opt/bitnami/php/etc/php.ini
```

Also, I think it should be included in the image, but ensure you run this command:
```
apt-get install php5-pgsql
```

**Comment by richb201** [comment]
The problem is that I need the debugger running. You realize that I don't
have the /opt/bitnami/php/etc directory on my PC? Perhaps, I should have
installed that? I get around that by appending the xdebug statements on to
the php.ini in the container. Thanks, you realize I am using php 7.2?

**Comment by miguelaeh** [comment]
Hi @richb201 ,
It is not necessary for you to have that directory locally. Thgat command is going to be executed inside the docker image, so you will obtain the content of the php.ini file use in the docker image.
Also, if you want to specify the version use a tag in the image name in this way:
```
docker run --rm -it bitnami/php-fpm:<tag> cat /opt/bitnami/php/etc/php.ini
```

You can find all the possible tags here: https://hub.docker.com/r/bitnami/php-fpm/tags

**Comment by richb201** [comment]
Thx, I looked for one that enabled postgres and couldn't  find it. Now I
tried modifying my Dockerfile and now my docker compose will not operate
successfully. I tried using the original Dockerfile, but it still won't
work. I can't bring up the system. Trying to use Docker was a huge mistake.
Unfortunately, getting rid of docker will not be that easy.

**Comment by rafariossaa** [comment]
Hi,
  You need to enable the postgresql extension, in order to do that you need to add an additional `.ini` file that will be loaded in addition to `php.ini`. You can see the instructions [here](https://github.com/bitnami/bitnami-docker-php-fpm/#user-content-add-additional-ini-files).

  This is an example using only the php-fpm container:
- Create a `pg.ini` file with the following content:
```
 extension = pdo_pgsql
```
- Run the container using the additiona `ini` file:
```
$ docker run --rm -v $PWD/pg.ini:/opt/bitnami/php/etc/conf.d/pg.ini -it bitnami/php-fpm bash
```
- As in this example we are indicating that we want to run `bash`, a terminal will be open inside the container. Now if we run phpinfo we can see that we have postgresql enabled.
```
root@3cdae1a427a2:/app# echo "<?php phpinfo(); ?>" | php | grep -i postgre
PDO Driver for PostgreSQL => enabled
PostgreSQL(libpq) Version => 11.7 (Debian 11.7-0+deb10u1)
```
- The exit the container bash terminal:
```
root@3cdae1a427a2:/app# exit
exit
~$ 
```
You can get the list of extensions that can be enabled by running:
```
 docker run --rm -it bitnami/php-fpm ls /opt/bitnami/php/lib/php/extensions
```

I hope this helps.
