### ISSUE TITLE
Always connect to the database by an unknown username, even the database.php is set

### ISSUE THREAD

**Issue by duomoteng** [bitnami/bitnami-docker-codeigniter#85]
Like the pic below. Even the password and username is set in database.php. The error is still showing up.
<img width="1208" alt="Screen Shot 2020-10-04 at 02 34 11" src="https://user-images.githubusercontent.com/48649432/94999172-34b9a580-05ea-11eb-90f4-ab9d4e0b6f02.png">
<img width="485" alt="Screen Shot 2020-10-04 at 02 34 22" src="https://user-images.githubusercontent.com/48649432/94999174-35ead280-05ea-11eb-992c-5c3bd577d171.png">

**Comment by miguelaeh** [comment]
Hi @duomoteng ,
How are you deploying the application? Are you using docker-compose? Could you share it?
