### ISSUE TITLE
Changes are not automatically shown, but on docker-compose restart

### ISSUE THREAD

**Issue by nbiuk** [bitnami/bitnami-docker-codeigniter#86]
Hello,

I have a new plain codeigniter project. I don't understand why, when I change some HTML, the change appears only a few minutes after the first refresh, or when I restart the docker-compose. What I'm doing wrong?

**Comment by FraPazGal** [comment]
Hi @nbiuk,

I have tried to reproduce the issue and I have similar problems. Although it is not as long as minutes, it does spend more than 30 seconds to sync the changes. 

It seems this is not an error from your end or from the container. The synchronisation time of shared filesystems on docker is a known issue, one specially bad on Mac as discussed here https://github.com/docker/for-mac/issues/77

**Comment by nbiuk** [comment]
Hi @FraPazGal, 
 
thank you for your reply! 

Yes, afterwards I also noticed for about 30, but it's still a long time!
I'm on a Linux machine and I'm new to docker.

It's also interesting that the outputs in the browser appears with a delay, but in the container, when I concat the file, the change is visible instantly!

And also, when I try to change a simple txt file outside the codeigniter application it works instantly in the browser too (example: localhost:8000/test.txt). So I wonder if the problem is maybe on the image itself.

For now I'm on apache, but if someone has a solution for this, I would be very thankful, because the initial idea was to make this project with docker!

**Comment by FraPazGal** [comment]
Hi @nbiuk,

If the change is instantly present when you `cat` the file from within the container, that cross out the possible mounted volume delay cause.

From what you are explaining, it seems the problem could be from the application itself. Did you create the `test.txt` file in the mounted folder as well or directly inside the container?

**Comment by nbiuk** [comment]
I've created it in the mounted folder.

**Comment by FraPazGal** [comment]
Hi @nbiuk,

That would mean that the issue comes from the application itself and in that case we have very few options. I'll see if there is any problem performance wise and come back with my findings!

**Comment by nbiuk** [comment]
Ok, thank you! I'll be patient.

**Comment by FraPazGal** [comment]
Hello @nbiuk!

I have investigated this and I haven't found any performance issues on our end. It seems this may be related to the `ttl` of chached elements (under `system/libraries/Cache`), which is set to 60 seconds. 

This would be in line with the observed behaviour where there is a timed wait of ~60s between two changes and where, if we change something after leaving the app idle for more than 1 minute, the change would display instantly on the browser. This is a non-configurable parameter of the application itself and there seems to be no effect upon changing these values post-installation, so unfortunately we may not be able to provide a fix on our end.

**Comment by nbiuk** [comment]
Hi FraPazGal,

i've seen your comment today, I'm sorry. Thank you for your investigation. But now I do not understand what I can do, if the parameter is not configurable?

Best regards
Nino

**Comment by FraPazGal** [comment]
Hi @nbiuk,

I have created an internal task to investigate a possible solution for this. Given the nature of the issue and the full backlog of the team in the short-term, I can't give you an ETA on this. In the meantime, I hope you can use our container despite the 60s ttl. Thank you for your understanding!

**Comment by nbiuk** [comment]
In the meantime I'll use the official CI installation (v. 3.1.11), without docker. Thank you :)

**Comment by rafariossaa** [comment]
Hi,
  We have made a new release of codeigniter where opcache is disabled, Could you give it a try ?

**Comment by nbiuk** [comment]
Hi, I've totally forget about this. In the past few months I had so much to do. I'll try it, of course! Thank you!

**Comment by nbiuk** [comment]
It's working perfectly! Thank you again and sorry again!
