### ISSUE TITLE
How to enable mod_rewrite in codeigniter docker image ?

### ISSUE THREAD

**Issue by bimalendu** [bitnami/bitnami-docker-codeigniter#89]
Hi, I was wondering how to enable mod_rewrite in the codeigniter docker image. Any help is highly appreciated ?

**Comment by bimalendu** [comment]
I had noticed that php is being used to serve files instead of apache from the line mentioned below: 
` CMD ["php" "-S" "0.0.0.0:8000"]`

Is there any way to address the mod_rewrite issue with php serving the files ?

**Comment by andresbono** [comment]
Hi @bimalendu, the purpose of this container is help with the development. For simplicity, the CMD is using the built-in web server of PHP to expose the application. As you can see in the Dockerfile, Apache is not included in this image.

**Comment by bimalendu** [comment]
Hi @andresbono, I used a lamp based docker image as a workaround solution to solve my issue. The lamp based docker repository can be found here: `https://github.com/sprintcube/docker-compose-lamp/tree/master`

**Comment by andresbono** [comment]
Thanks for letting us know, @bimalendu.
