### ISSUE TITLE
Override PHP version

### ISSUE THREAD

**Issue by bagendahl** [bitnami/bitnami-docker-codeigniter#91]
Is it possible to change or override php version in docker-compose? If not, how can I bump up the PHP version to 7.4?

Thanks in advance,
Patrick

**Comment by alvneiayu** [comment]
hi @bagendahl 

No, I don't think so. The only solution that you can do is modify the Dockerfile to use the specific PHP version that you want and then use the image built by yourself in the docker-compose.

Thanks a lot

Álvaro
