### ISSUE TITLE
database config file has wrong format 

### ISSUE THREAD

**Issue by howtomakeaturn** [bitnami/bitnami-docker-codeigniter#92]
Hi

I followed the documentation to do this:

```
$ mkdir ~/myapp && cd ~/myapp
$ curl -LO https://raw.githubusercontent.com/bitnami/bitnami-docker-codeigniter/master/docker-compose.yml
$ docker-compose up
```

and then in the application/config/database.php

I get this:

```
$db['default'] = array(
    'dsn' => '',
    'hostname' => 'mariadb',
    'database_user' => 'bn_app',
    'database_password' => 'EJ20wgrDH6',
    'databasename' => 'bitnami_app',
    // skip the rest
);
```

Which cannot be loaded by codeigniter framework.

I think the array keys should be corrected with

`database_user` -> `username`
`database_password` -> `password`
`databasename` -> `database`

Is there any codeigniter version related bug here?

Thank you very much!

**Comment by carrodher** [comment]
Hi, thanks for letting us know. In order to investigate the issue internally, what is the error you're receiving? Is the error solved when you perform the suggested modifications? Thanks

**Comment by howtomakeaturn** [comment]
Hi, the error is 

```
A PHP Error was encountered
Severity: Warning

Message: mysqli::real_connect(): (HY000/1045): Access denied for user ''@'192.168.160.3' (using password: NO)

Filename: mysqli/mysqli_driver.php

Line Number: 203

Backtrace:

File: /app/myapp/application/controllers/Welcome.php
Line: 23
Function: database

File: /app/myapp/index.php
Line: 315
Function: require_once
```

and the error is solved when I perform the suggested modifications.

so I think there's a bug during the Codeigniter app creating procedure.

**Comment by carrodher** [comment]
I see, thank you very much for the detailed explanation. I think it is something we can fix on the Bitnami logic, I am creating an internal task to work on it.

I will set the `on-hold` label to prevent the stale bot from closing this issue while we work on the solution.
Thanks again!

**Comment by carrodher** [comment]
The issue should be solved with this commit https://github.com/bitnami/bitnami-docker-codeigniter/commit/2373c87ccda3128ae7aae0c61881c716469054e7, the changes should be available in the following container images tags: `3`, `3-debian-10`, `3.1.11`, `3.1.11-debian-10-r504`, `latest`.

I tested the solution and this is the result:
```console
root@819ac472aa6f:/app# cat myapp/application/config/database.php
$db['default'] = array(
	'dsn'	=> '',
	'hostname' => 'mariadb'
	'username' => 'bn_app'
	'password' => '59tp6dMO7F'
	'database' => 'bitnami_app'
	'dbdriver' => 'mysqli',
	'dbprefix' => '',
	'pconnect' => FALSE,
	'db_debug' => (ENVIRONMENT !== 'production'),
	'cache_on' => FALSE,
	'cachedir' => '',
	'char_set' => 'utf8',
	'dbcollat' => 'utf8_general_ci',
	'swap_pre' => '',
	'encrypt' => FALSE,
	'compress' => FALSE,
	'stricton' => FALSE,
	'failover' => array(),
	'save_queries' => TRUE
);
```

I hope the issue is solved for you with those changes!
