### ISSUE TITLE
chmod: changing permissions of '/proc/self/fd/1': Permission denied

### ISSUE THREAD

**Issue by DanteSkylar** [bitnami/bitnami-docker-codeigniter#96]
### Name and Version

docker.io/bitnami/codeigniter:4

### What steps will reproduce the bug?

Docker version 1.13.1, build 7d71120/1.13.1

### What do you see instead?

![qweqweqweqeqeq](https://user-images.githubusercontent.com/23350857/160237785-b5810987-142b-4db6-8987-f31489fdd347.png)

**Comment by rafariossaa** [comment]
Please, [note the Bitnami team is not actively monitoring GitHub Issues for this project](https://github.com/bitnami/bitnami-docker-codeigniter#community-supported-solution). This issue will stay open for 20 days to allow the community to contribute, after 15 days without activity the issue will be marked as stale being closed after 5 days.
If you would like to contribute to this container image by fixing a bug or adding a new feature feel free to create a PR, the Bitnami team will be happy to review it and provide feedback.

**Comment by DanteSkylar** [comment]
Selinux problem
set selinux into permissive mode

my bad. thx

**Comment by rafariossaa** [comment]
Thanks for coming back and sharing your findings.
